version: "3.8"

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://auth-service:5001
      - COURSE_SERVICE_URL=http://course-service:5002
      - GRADE_SERVICE_URL=http://grade-service:5003
    networks:
      - app-network
    restart: unless-stopped

  # Authentication Service
  auth-service:
    build:
      context: ./src/app/services/auth
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=supersecretkey
      - MONGO_URI=mongodb+srv://markdcg:7fCgFVpVrJ8ewNLe@cluster0.pysivmn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  # Course Service
  course-service:
    build:
      context: ./src/app/services/course
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://markdcg:7fCgFVpVrJ8ewNLe@cluster0.pysivmn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  # Grade Service
  grade-service:
    build:
      context: ./src/app/services/grade
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb+srv://markdcg:7fCgFVpVrJ8ewNLe@cluster0.pysivmn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  # Shared MongoDB
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    command: mongod --bind_ip_all

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
