version: '3.8'

services:
  course-api:
    build: .
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb+srv://markdcg:7fCgFVpVrJ8ewNLe@cluster0.pysivmn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
